spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/germinar
    username: postgres
    password: pa55w0rd

cognito:
  clientId:  ${AWS_COGNITO_APP_CLIENT_ID}
  clientSecret: ${COGNITO_CLIENT_SECRET}
  userPoolId: ${AWS_COGNITO_POOL_ID}
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}

