spring:
  application:
    name: api
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

germinar:
  integrations:
    perenual:
      api-key: ${PERENUAL_API_KEY}

    plantnet:
      api-key: ${PLANTNET_API_KEY}

    freeimage:
      api-key: ${FREEIMAGE_API_KEY}

    trefle:
      api-key: ${TREFLE_API_KEY}

    weather:
      api-key: ${WEATHER_API_KEY}

    plant-id:
      api-key: ${PLANTID_API_KEY}

    crop-kindwise:
      api-key: ${CROPKINDWISE_API_KEY}

