spring:
  application:
    name: api
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

germinar:
  integrations:
    perenual:
      api-key: ${PERENUAL_API_KEY}

    plantnet:
      api-key: ${PLANTNET_API_KEY}

    freeimage:
      api-key: ${FREEIMAGE_API_KEY}

    trefle:
      api-key: ${TREFLE_API_KEY}

    weather:
      api-key: ${WEATHER_API_KEY}

    plant-id:
      api-key: ${PLANTID_API_KEY}

cognito:
  clientId:  ${AWS_COGNITO_APP_CLIENT_ID}
  clientSecret: ${COGNITO_CLIENT_SECRET}
  userPoolId: ${AWS_COGNITO_POOL_ID}

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
