insert into garden.diseases_candidate (scientific_name_disease,
                                       name,
                                       type,
                                       eppo_code,
                                       common_names,
                                       kingdom_taxonomy,
                                       entity_id,
                                       class_taxonomy,
                                       genus_taxonomy,
                                       order_taxonomy,
                                       family_taxonomy,
                                       phylum_taxonomy,
                                       language,
                                       wiki_urls)
values (:scientificNameDisease,
        :name,
        :type,
        :eppoCode,
        :commonNames,
        :kingdomTaxonomy,
        :entityId,
        :classTaxonomy,
        :genusTaxonomy,
        :familyTaxonomy,
        :phylumTaxonomy,
        :language,
        :wikiUrls);
