insert into garden.plant_catalog (scientific_name,
                                  description,
                                  slug_scientific_name,
                                  genus,
                                  family_name,
                                  max_size,
                                  fertilizer,
                                  watering_frecuency,
                                  pruning,
                                  soil,
                                  insecticide,
                                  tips)
values (:scientific_name,
        :description,
        :slug_scientific_name,
        :genus,
        :family_name,
        :max_size,
        :fertilizer,
        :watering_frecuency,
        :pruning,
        :soil,
        :insecticide,
        :tips);

-- //TODO: agregar los demas atributos que va a necesitar este plant catalog.
