insert into garden.plant (alias,
                          id_garden,
                          notes,
                          user_id,
                          id_plants_catalog,
                          creation_date,
                          modification_date,
                          height,
                          planting_date,
                          is_active)
values (:alias,
        :idGarden,
        :notes,
        :idUser,
        :idPlantCatalog,
        now(),
        now(),
        :height,
        :plantingDate,
        true);
